{"name": "test_assume", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest/test_order.py:17: AssumptionFailure\n>>\tpytest.assume(2==0)\nAssertionError: assert False\n\ntest/test_order.py:18: AssumptionFailure\n>>\tpytest.assume(1==2)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test/test_order.py:17: AssumptionFailure\nE               >>\tpytest.assume(2==0)\nE               AssertionError: assert False\nE               \nE               test/test_order.py:18: AssumptionFailure\nE               >>\tpytest.assume(1==2)\nE               AssertionError: assert False\n\n/usr/local/lib/python3.8/site-packages/six.py:702: FailedAssumption"}, "attachments": [{"name": "stdout", "source": "59c46194-4caa-484d-bcc5-02b8f2020672-attachment.txt", "type": "text/plain"}], "start": 1614868374075, "stop": 1614868374074, "uuid": "d8b2fae3-f1ba-4cfb-9e10-42942daf8ae5", "historyId": "6fed2e55462e68282567aae498b76ef9", "testCaseId": "957ba7de5f95ba79c805aa489f1c26d2", "fullName": "test.test_order#test_assume", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_order"}, {"name": "host", "value": "avivatangdeMacBook-Pro.local"}, {"name": "thread", "value": "68145-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_order"}]}